version: "3.7"

services:
  meleton_nginx:
    container_name: meleton_nginx
    build: ./docker/nginx
    restart: always
    ports:
      - "8080:80"
    links:
      - meleton_php
    volumes:
      - ./docker/nginx/conf/hosts/:/etc/nginx/conf.d/
      - ./laravel:/var/www

  meleton_php:
    container_name: meleton_php
    build: ./docker/php
    restart: always
    volumes:
      - ./laravel:/var/www

  meleton_db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./storage/mysql:/var/lib/mysql
